#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 2.2.0.{build}
install:
    # Needed for publishing of examples, build worker defaults to core.autocrlf=input.
    - git config --global core.autocrlf true
    - git clone https://github.com/PowerShell/DscResource.Tests

    - ps: |
        $moduleName = 'WSManDsc'
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask

#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -CodeCoverage `
            -CodeCovIo

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

# scripts to run before deployment
deploy_script:
    - ps: |
        Invoke-AppveyorAfterTestTask `
            -Type 'Wiki' `
            -ResourceModuleName $moduleName
